django_live/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('onlineshop.urls')),
]

onlineshop/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'onlineshop'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:product_id>', views.detail, name='detail'),
    path('input_product', views.input_product, name='input_product'),
    path('index_update', views.index_update, name='index_update'),
    

]

onlineshop/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    image_path = models.CharField(max_length=500)
    name = models.CharField(max_length=255)
    price = models.CharField(max_length=20)
    
    def __str__(self):
        return self.name


class DescribeProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    descipt = models.TextField(max_length=2000)

onlineshop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from .models import Product, DescribeProduct

# Create your views here.

def index(request):
    product = Product.objects.all()
    return render (request, 'onlineshop/index.html', {'products': product})

def input_product(request):
    return render(request, 'onlineshop/form.html',{})
    
def detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    dummy = DescribeProduct.objects.get(pk=product_id)
    list_desc = dummy.descipt.split(',')
    
    return render (request, 'onlineshop/detail.html', {'product': product, 'list_desc':list_desc})

def index_update(request):
    image_path          = request.POST['image_path']
    product_name        = request.POST['product_name']
    price               = request.POST['price']
    description         = request.POST['description']

    newproduct = Product(image_path=image_path, name=product_name, price=price)
    newproduct.save()
    newdesc = DescribeProduct(product=newproduct, descipt=description)
    newdesc.save()

    product = Product.objects.all()
    return render (request, 'onlineshop/index.html', {'products': product})

onlineshop/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Toko Online</title>
    {%load static%}
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
    <link rel="stylesheet" href="{%static 'js/bootstrap.min.js'%}">
    <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
</head>

<!------------------------------------------- header ------------------------------------------->
<header>
    <div class="wrap-container--header">
        <div class="container">
            <div class="row align-items-center blok-header">
                <div class="col-md-6 align-items-center company-name">
                    Toko Online
                </div>
                <div class="col-md-6">
                    <div class="header-nav">
                        <ul class="header-nav__list list-unstyled">  
                            <li> 
                                <a href="{%url 'onlineshop:index'%}">Home</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!------------------------------------------- EOF header ------------------------------------------->

<body>
    <div class="wrap-base--content">
        {% block content %}
        {% endblock %}        
    </div>
</body>

</html>

onlineshop/templates/onlineshop/detail.html
{%extends 'base.html'%}
{%block title%}Detail Product {{product.name}}{%endblock%}

{%block content%}
<div class="wrap-product--detail">
    <div class="container-fluid d-flex justify-content-center">
        <div class="wrap-product_specify">
            <div class="product-image">
                <img src="{{product.image_path}}" alt="">
            </div>
            <div class="product-name">
                {{product.name}}
            </div>
            <div class="product-price">
                {{product.price}}
            </div>
            <!-- product description -->
            <div class="wrap-pro--desc">
                <div class="pro-desc--text">
                    Deskripsi Product
                </div>
                <div class="pro-desc--list">
                    <ul>
                        {%for desc in list_desc%}
                        <li>{{ desc }}</li>
                        {%endfor%}
                    </ul>
                </div>
            </div>
        </div>
    </div>    
</div>

{%endblock%}

onlineshop/templates/onlineshop/form.html
{%extends 'base.html'%}
{%block title%}Toko Online{%endblock%}


{%block content%}
<div class="wrap-input_product">
        <form action="{%url 'onlineshop:index_update'%}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="image_path">Image Path</label>
                <input class="form-control" type="text" placeholder="https://picsum.photos/200/300" name="image_path" id="image_path">        
            </div>
            <div class="form-group">
                <label for="product_name">Product Name</label>
                <input type="text" class="form-control" placeholder="Sepatu Vans" name="product_name" id="product_name">        
            </div>
            
            <div class="form-group">
                <label for="price">Price</label>
                <input type="text" class="form-control" placeholder="799.000" name="price" id="price">        
            </div>
            
            <div class="form-group">
                <label for="description">Content</label>
                <textarea name="description" class="form-control" id="description" cols="30" rows="10"></textarea>        
            </div>
    
            <!-- <input type="submit" value="Submit New Content"> -->
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{%endblock%}

onlineshop/templates/onlineshop/index.html
{%extends 'base.html'%}
{%block title%}Toko Online{%endblock%}


{%block content%}
<div class="container">
    <div class="row d-flex justify-content-center">
        {%for product in products%}
        <div class="col-4">
            <div class="wrap-index border-dark rounded">
                <div class="product-image">
                    <img style="max-width: 100%;" src="{{product.image_path}}" alt="">
                </div>
                <div class="product-name">
                    {{product.name}}
                </div>
                <div class="product-price">
                    {{product.price}}
                </div>
                <div class="detail-product">
                    <a href="{%url 'onlineshop:detail' product.id%}" class="lihatdetail">Lihat Detail</a>
                </div>
            </div>
        </div>
        {%endfor%}
    </div>
</div>
<div class="add-product">
    <form class="d-flex justify-content-center" action="/input_product" method="GET">
        <button type="submit" class="btn btn-success submit-content">Submit New Content</button>
    </form>
</div>
{%endblock%}